version: '3.8'

services:
  # ============================================
  # ПРИЛОЖЕНИЕ (дано разработкой)
  # ============================================

  msr-db:
    container_name: msr-db
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d my-shows-rating"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

  msr-backend:
    container_name: msr-backend
    image: gitlab.qa.studio:5050/manual-qa/my-shows-rating/backend:v1.0.0
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      msr-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/api/v1/series"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test-network

  # ============================================
  # ТЕСТЫ (добавлено QA)
  # ============================================

  api-tests:
    container_name: msr-api-tests                     # имя контейнера с тестами
    build:                                            # инструкция для сборки образа
      context: .                                      # контекст сборки – текущая папка
      dockerfile: Dockerfile                          # путь к Dockerfile
    depends_on:                                       # зависимость от других сервисов
      msr-backend:                                    # ждём готовности бэкенда
        condition: service_healthy                    # условие – healthcheck пройден
    environment:                                      # переменные окружения для контейнера
      API_BASE_URL: http://msr-backend:8000/api/v1    # подключение к API внутри Docker-сети
      POSTGRES_DB: my-shows-rating                    # подключение к БД внутри Docker-сети
      POSTGRES_USER: postgres                         # пользователь БД
      POSTGRES_PASSWORD: "123456"                     # пароль БД
      POSTGRES_HOST: msr-db                           # хост БД (имя сервиса в сети)
      POSTGRES_PORT: "5432"                           # порт БД
    networks:
      - test-network                                  # подключение к общей сети для доступа к msr-db и msr-backend
    volumes:
      - ./allure-results:/app/allure-results          # создаём локальную папку для Allure-результатов
    # запускаем pytest с сохранением отчётов Allure в allure-results и очисткой старых
    command: [ "pytest", "-v", "--alluredir=/app/allure-results", "--clean-alluredir" ]

networks:
  test-network:
    driver: bridge
